"""added password column into db, other tests

Revision ID: 1608dfb74f97
Revises: 4dc7c1394549
Create Date: 2025-02-12 17:38:31.145364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1608dfb74f97'
down_revision = '4dc7c1394549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
