"""test running migrations

Revision ID: 1967a100b20e
Revises: a5f9acde4d83
Create Date: 2025-02-12 17:37:44.110422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1967a100b20e'
down_revision = 'a5f9acde4d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
