"""test running migrations

Revision ID: 382cc985ec1c
Revises: ed8070f61fc1
Create Date: 2025-02-12 14:21:27.121106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382cc985ec1c'
down_revision = 'ed8070f61fc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
