"""added password column into db, other tests

Revision ID: a5f9acde4d83
Revises: cee79692e2e4
Create Date: 2025-02-12 17:37:05.255008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f9acde4d83'
down_revision = 'cee79692e2e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
