"""test running migrations

Revision ID: af134ff97533
Revises: 4f7486dcadb1
Create Date: 2025-02-12 14:04:58.097013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af134ff97533'
down_revision = '4f7486dcadb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
