"""test running migrations

Revision ID: c018dc077c1f
Revises: df90e808037f
Create Date: 2025-02-12 17:44:38.404883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c018dc077c1f'
down_revision = 'df90e808037f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
