"""test running migrations

Revision ID: dc032c889dcc
Revises: af134ff97533
Create Date: 2025-02-12 14:09:04.260023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc032c889dcc'
down_revision = 'af134ff97533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
