"""test running migrations

Revision ID: e7d112f9df83
Revises: dc032c889dcc
Create Date: 2025-02-12 14:11:00.291048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d112f9df83'
down_revision = 'dc032c889dcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
