"""test running migrations

Revision ID: ed8070f61fc1
Revises: e7d112f9df83
Create Date: 2025-02-12 14:21:10.503493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8070f61fc1'
down_revision = 'e7d112f9df83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
